{
 "title": "SLOpPy Pizza Design API - FastAPI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   {
    "name": "api_endpoint",
    "query": {
     "query": "label_values(sli:request_duration:binary, handler)"
    }
   },
   { "name": "slo_target", "query": "0.9,0.99,0.999" }
  ]
 },
 "panels": [
  {
   "title": "$api_endpoint avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{handler=\"$api_endpoint\",status=\"2xx\"} / http_request_duration_seconds_count"
    },
    {
     "expr": "sli:request_duration:binary{handler=\"$api_endpoint\"}"
    }
   ]
  },
  {
   "title": "$api_endpoint availability (latency SLI)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sli:request_duration:binary{handler=\"$api_endpoint\"}[15m])"
    }
   ]
  },
  {
   "title": "$api_endpoint SLO achievement",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sli:request_duration:binary{handler=\"$api_endpoint\"}[15m])/$slo_target"
    }
   ]
  },
  {
   "title": "$api_endpoint error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"$api_endpoint\",status!=\"2xx\"}[60s])"
    },
    {
     "expr": "sli:error_rate:binary{handler=\"$api_endpoint\"}"
    }
   ]
  },
  {
   "title": "$api_endpoint availability (latency SLI)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sli:error_rate:binary{handler=\"$api_endpoint\"}[15m])"
    }
   ]
  },
  {
   "title": "$api_endpoint SLO achievement",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sli:error_rate:binary{handler=\"$api_endpoint\"}[15m])/$slo_target"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(http_requests_total{job=\"prometheus\"}[1m])",
       "legendFormat": "{{ method }} {{ handler }}"
      }
     ]
    },
    {
     "title": "Request per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(http_requests_total[1m]))",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Request duration [s] - p50",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "clocks" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Request duration [s] - p90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "clocks" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  }
 ]
}